import type { DesktopBridgeApi } from "@planweave-ai/runtime";

export type DesktopBridgeInvokeMethod = Exclude<keyof DesktopBridgeApi, "onPackageFileChanged">;

export const desktopBridgeInvokeChannels = {
  addBlock: "planweave:addBlock",
  addDependencyEdge: "planweave:addDependencyEdge",
  addTaskNode: "planweave:addTaskNode",
  chooseProjectFolder: "planweave:chooseProjectFolder",
  createPackageFileSnapshot: "planweave:createPackageFileSnapshot",
  createTaskCanvas: "planweave:createTaskCanvas",
  createTaskDraft: "planweave:createTaskDraft",
  detectAgentTools: "planweave:detectAgentTools",
  detectRuntimeTools: "planweave:detectRuntimeTools",
  detectPackageFileChanges: "planweave:detectPackageFileChanges",
  getAutoRunState: "planweave:getAutoRunState",
  getBlockDetail: "planweave:getBlockDetail",
  getDesktopLayout: "planweave:getDesktopLayout",
  getDirtyPromptRefs: "planweave:getDirtyPromptRefs",
  getFeedbackRecords: "planweave:getFeedbackRecords",
  getGraphViewModel: "planweave:getGraphViewModel",
  getLatestAutoRunSummary: "planweave:getLatestAutoRunSummary",
  getProjectExecutionPlan: "planweave:getProjectExecutionPlan",
  getProjectOverview: "planweave:getProjectOverview",
  getReviewAttempts: "planweave:getReviewAttempts",
  getReviewPipeline: "planweave:getReviewPipeline",
  getRunRecord: "planweave:getRunRecord",
  getStatistics: "planweave:getStatistics",
  getTaskDetail: "planweave:getTaskDetail",
  getTaskExecutionOrder: "planweave:getTaskExecutionOrder",
  getTodoGroups: "planweave:getTodoGroups",
  initOrOpenProject: "planweave:initOrOpenProject",
  listBlockRunRecords: "planweave:listBlockRunRecords",
  listProjects: "planweave:listProjects",
  openBlockInspectorWindow: "planweave:openBlockInspectorWindow",
  openTaskInspectorWindow: "planweave:openTaskInspectorWindow",
  openProject: "planweave:openProject",
  pauseAutoRun: "planweave:pauseAutoRun",
  refreshChangedPackagePrompts: "planweave:refreshChangedPackagePrompts",
  refreshPackageFileChanges: "planweave:refreshPackageFileChanges",
  readProjectPrompt: "planweave:readProjectPrompt",
  readProjectPromptPolicy: "planweave:readProjectPromptPolicy",
  removeBlock: "planweave:removeBlock",
  removeDependencyEdge: "planweave:removeDependencyEdge",
  removeProject: "planweave:removeProject",
  removeTaskCanvas: "planweave:removeTaskCanvas",
  removeTaskNode: "planweave:removeTaskNode",
  resetDesktopLayout: "planweave:resetDesktopLayout",
  resumeAutoRun: "planweave:resumeAutoRun",
  revealPathInFinder: "planweave:revealPathInFinder",
  revealProjectInFinder: "planweave:revealProjectInFinder",
  saveDesktopLayout: "planweave:saveDesktopLayout",
  searchProject: "planweave:searchProject",
  startAutoRun: "planweave:startAutoRun",
  stopAutoRun: "planweave:stopAutoRun",
  unblockBlock: "planweave:unblockBlock",
  unwatchPackageFiles: "planweave:unwatchPackageFiles",
  updateBlockExecutor: "planweave:updateBlockExecutor",
  updateBlockPrompt: "planweave:updateBlockPrompt",
  updateBlockTitle: "planweave:updateBlockTitle",
  updateProjectPrompt: "planweave:updateProjectPrompt",
  updateReviewPipeline: "planweave:updateReviewPipeline",
  updateProjectPromptPolicy: "planweave:updateProjectPromptPolicy",
  updateTaskExecutor: "planweave:updateTaskExecutor",
  updateTaskPrompt: "planweave:updateTaskPrompt",
  updateTaskTitle: "planweave:updateTaskTitle",
  validateGraphEdit: "planweave:validateGraphEdit",
  watchPackageFiles: "planweave:watchPackageFiles"
} as const satisfies Record<DesktopBridgeInvokeMethod, string>;

export const packageFileChangedChannel = "planweave:packageFileChanged";
